# Podfile for Smart Glasses Gateway iOS App
# Install: pod install

platform :ios, '15.0'

target 'SmartGlassesGateway' do
  use_frameworks!

  # WebSocket client
  pod 'Starscream', '~> 4.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
